version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: taskmanager-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: akaddour
      POSTGRES_PASSWORD: akaddour
      POSTGRES_DB: taskmanager_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
